<?php
    echo '666';
?>

<div class="sold-amount">
    <span>

        sdfsdsdfsdfsdfsdfsdf;

    </span>
</div>







<!--<div class="sold-amount">-->
<!--    <span>-->
<!--    --><?php
//    $productId = $this->getProduct()->getId();
//
//    $helper = Mage::helper('wizmagstatist');
//    $quantity = $helper->getProductQuantity($productId);
//
//    if($quantity!=0) {
//        echo 'Sold: ' . $quantity . '<br>';
//    } else {
//        echo 'You can be the first who buy this the product!';
//    }
//
//
//    ?>
<!---->
<!--    </span>-->
<!--</div>-->



