<script>
    function ajaxSold()
    {

//        $(document).ready(function(){
//            $('#show_btn').click(function(){
//                $.ajax({
//                    url: 'ajax_servlet.php',
//                    data: 'id='+$('#pos_id').val(),
//                    cache: false,
//                    success: function(html){
//                        $('#content').html(html);
//                    }
//                });
//            });
//            $('#close_btn').click(function(){
//                $('#content').html('');
//            });
//        });

    }
</script>


<div class="sold-amount">
    <span>
        <?php
            $productId = $this->getProduct()->getId();

            $helper = Mage::helper('wizmagstatist');
            $quantity = $helper->getProductQuantity($productId);
            if($quantity!=0) {
                echo 'Sold: '; ?> <a href='' id="show_quantity"> <?php echo $quantity; ?> </a> <?php echo '<br>';
            } else {
                echo 'You can be the first who buy this the product!';
            }
        ?>
        <script src="ajax.js" type="text/javascript"></script>
    </span>
</div>









<script>
//    function ajaxSold()
//    {
//        <?php
//        $productId = $this->getProduct()->getId();
//        $helper = Mage::helper('wizmagstatist');
//        $quantity = $helper->getProductQuantity($productId);
//        echo $quantity;
//        ?>
//    }
</script>


<!--<div class="sold-amount">-->
<!--    <span>-->
<!--        --><?php
//        $productId = $this->getProduct()->getId();
//
//        $helper = Mage::helper('wizmagstatist');
//        $quantity = $helper->getProductQuantity($productId);
//        if($quantity!=0) {
//            echo 'Sold: '; ?><!-- <a href='' onclick="return ajaxSold(this);"> --><?php //echo $quantity; ?><!-- </a> --><?php //echo '<br>';
//        } else {
//            echo 'You can be the first who buy this the product!';
//        }
//        ?>
<!--    </span>-->
<!--</div>-->






<!--<!--it's work version of exstention;-->-->
<!--<div class="sold-amount">-->
<!--    <span>-->
<!--    --><?php
//    $productId = $this->getProduct()->getId();
//
//    $helper = Mage::helper('wizmagstatist');
//    $quantity = $helper->getProductQuantity($productId);
//
//    if($quantity!=0) {
//        echo 'Sold: ' . $quantity . '<br>';
//    } else {
//        echo 'You can be the first who buy this the product!';
//    }
//
//
//    ?>
<!---->
<!--    </span>-->
<!--</div>-->
