<div class="sold-amount">
    <span>
        <?php
            $productId = $this->getProduct()->getId();

            $helper = Mage::helper('wizmagstatist');
            $quantity = $helper->getProductQuantity($productId);

            if($quantity!=0) {
            //                echo 'Sold: '; ?><!-- <a href='' id="show_quantity" onclick="ajaxSold()"> --><?php //echo $quantity; ?><!-- </a> --><?php //echo '<br>';
            echo 'Sold: '; ?> <a href='javascript:;' id="show_quantity" > <?php echo $quantity; ?> </a> <?php echo '<br>';
            } else {
                echo 'You can be the first, who buy this the product!';
            }
        ?>
    </span>
</div>

<script>
    jQuery(document).ready(function(){
        jQuery('#show_quantity').click(function(){
            var productId = <?php echo $productId ?>;
//            var hrefValue = jQuery(this).attr('href');
            jQuery.ajax({
                url: '<?php echo $this->getUrl('wizmagstatist/index/getQty') ?>',
                type: 'POST',
                dataType: 'json',
                data: {'id':productId},
                cache: false,
                success: function(response){
//                    jQuery('#ggt').text('urlAmount');

                    //console.log(response);
                    //var json = response.evalJSON(true);
                    //console.log(json);
                    //console.log(response.qty);
                    jQuery('#show_quantity').text(response.qty);
                }
            });
        });
    });
</script>
